#!/bin/bash

. ./functions

exec_sql "drop table wnioski_wniosekzalacznik;"
exec_sql "drop table wnioski_wniosekhistoria;"
exec_sql "drop table wnioski_wniosek;"
exec_sql "drop table wnioski_adresat;"
exec_sql "drop table wnioski_miasto;"

