#!/bin/sh

. ./functions

insert_cities_sql=" \
	INSERT INTO wnioski_miasto (id, nazwa, szerokosc_geo, dlugosc_geo) VALUES \
		(1, 'Warszawa', 52.250934, 21.015869), \
		(2, 'Szczecin', 53.422817, 14.55817), \
		(3, 'Kraków', 50.060348, 19.941009), \
		(4, 'Łódź', NULL, NULL);"
	
insert_recieviers_sql=" \
   INSERT INTO wnioski_adresat (id, nazwa, miasto_id, szerokosc_geo, dlugosc_geo) VALUES \
		(1, 'Urząd Miasta Jelenia Góra', NULL, 50.903095, 15.734713), \
		(2, 'Urząd Miasta Legnica', NULL, 51.206583, 16.162372), \
		(3, 'Urząd Miejski Wrocławia', NULL, 51.110673, 17.037829), \
		(4, 'Urząd Miejski w Wałbrzychu', NULL, 50.767770, 16.282523), \
		(5, 'Urząd Miasta Bydgoszczy', NULL, 53.120221, 17.994030), \
		(6, 'Urząd Miejski w Grudziądzu', NULL, 53.493531, 18.748483), \
		(7, 'Urząd Miasta Torunia', NULL, 53.012696, 18.604033), \
		(8, 'Urząd Miasta Włocławek', NULL, 52.653465, 19.070383), \
		(9, 'Urząd Miasta Biała Podlaska', NULL, 52.034369, 23.117976), \
		(10, 'Urząd Miasta Chełm', NULL, 51.133922, 23.469425), \
		(11, 'Urząd Miasta Lublin', NULL, 51.247655, 22.565628), \
		(12, 'Urząd Miasta Zamość', NULL, 50.717861, 23.252638), \
		(13, 'Urząd Miasta Łodzi', NULL, 51.764487, 19.457613), \
		(14, 'Urząd Miasta Piotrkowa Trybunalskiego', NULL, 51.404905, 19.689540), \
		(15, 'Urząd Miasta Skierniewice', NULL, 51.956769, 20.141625), \
		(16, 'Urząd Miasta Krakowa', NULL, 50.058794, 19.936934), \
		(17, 'Urząd Miasta Nowego Sącza', NULL, 49.625100, 20.690982), \
		(18, 'Urząd Miasta Tarnowa', NULL, 50.015730, 20.986594), \
		(19, 'Urząd Miasta Ostrołęki', NULL, 53.084096, 21.567219), \
		(20, 'Urząd Miasta Płocka', NULL, 52.545280, 19.684687), \
		(21, 'Urząd Miejski w Radomiu', NULL, 51.401508, 21.158005), \
		(22, 'Urząd Miasta Siedlce', NULL, 52.167654, 22.273740), \
		(23, 'Urząd Miasta Stołecznego Warszawy', NULL, 52.243542, 21.007305), \
		(24, 'Urząd Miasta Opola', NULL, 50.668484, 17.922523), \
		(25, 'Urząd Miasta Krosna', NULL, 49.683923, 21.771089), \
		(26, 'Urząd Miejski w Przemyślu', NULL, 49.782597, 22.768870), \
		(27, 'Urząd Miasta Rzeszowa', NULL, 50.037362, 22.004035), \
		(28, 'Urząd Miasta Tarnobrzega', NULL, 50.571807, 21.669941), \
		(29, 'Urząd Miejski w Białymstoku', NULL, 53.134115, 23.172685), \
		(30, 'Urząd Miejski w Łomży', NULL, 53.178888, 22.082605), \
		(31, 'Urząd Miejski w Suwałkach', NULL, 54.098529, 22.927852), \
		(32, 'Urząd Miejski w Gdańsku', NULL, 54.351461, 18.641034), \
		(33, 'Urząd Miasta Gdyni', NULL, 54.509570, 18.538840), \
		(34, 'Urząd Miejski w Słupsku', NULL, 54.464742, 17.026312), \
		(35, 'Urząd Miasta Sopotu', NULL, 54.440029, 18.564829), \
		(36, 'Urząd Miejski w Bielsku-Białej', NULL, 49.821776, 19.050789), \
		(37, 'Urząd Miejski w Bytomiu', NULL, 50.350225, 18.911882), \
		(38, 'Urząd Miasta Chorzów', NULL, 50.297471, 18.953237), \
		(39, 'Urząd Miasta Częstochowy', NULL, 50.809663, 19.116058), \
		(40, 'Urząd Miejski w Dąbrowie Górniczej', NULL, 50.330890, 19.206548), \
		(41, 'Urząd Miasta Jastrzębie-Zdrój', NULL, 49.952794, 18.611854), \
		(42, 'Urząd Miejski w Jaworznie', NULL, 50.199549, 19.275344), \
		(43, 'Urząd Miasta Mysłowice', NULL, 50.240860, 19.141527), \
		(44, 'Urząd Miasta Piekary Śląskie', NULL, 50.375011, 18.944343), \
		(45, 'Urząd Miasta Ruda Śląska', NULL, 50.286018, 18.875011), \
		(46, 'Urząd Miasta Rybnika', NULL, 50.093768, 18.542111), \
		(47, 'Urząd Miejski w Sosnowcu', NULL, 50.278223, 19.133753), \
		(48, 'Urząd Miejski w Świętochłowicach', NULL, 50.285237, 18.931374), \
		(49, 'Urząd Miasta Tychy', NULL, 50.114674, 18.996909), \
		(50, 'Urząd Miejski w Zabrzu', NULL, 50.308476, 18.785432), \
		(51, 'Urząd Miasta Żory', NULL, 50.045160, 18.694688), \
		(52, 'Urząd Miejski w Gliwicach', NULL, 50.296365, 18.669057), \
		(53, 'Urząd Miasta Katowice', NULL, 50.258513, 19.021706), \
		(54, 'Urząd Miasta Siemianowice Śląskie', NULL, 50.305508, 19.028511), \
		(55, 'Urząd Miasta Kielce', NULL, 50.871843, 20.630796), \
		(56, 'Urząd Miejski w Elblągu', NULL, 54.161163, 19.408588), \
		(57, 'Urząd Miasta Olsztyna', NULL, 53.778758, 20.479866), \
		(58, 'Urząd Miejski w Koszalinie', NULL, 54.190955, 16.181209), \
		(59, 'Urząd Miasta Szczecin', NULL, 53.438240, 14.543200), \
		(60, 'Urząd Miasta Świnoujście', NULL, 53.913938, 14.238928), \
		(61, 'Urząd Miejski w Kaliszu', NULL, 51.762647, 18.089829), \
		(62, 'Urząd Miejski w Koninie', NULL, 52.214172, 18.255355), \
		(63, 'Urząd Miasta Leszna', NULL, 51.849315, 16.570765), \
		(64, 'Urząd Miasta Poznania', NULL, 52.406342, 16.935365), \
		(65, 'Urząd Miasta Gorzowa Wielkopolskiego', NULL, 52.731734, 15.242509), \
		(66, 'Urząd Miasta Zielona Góra', NULL, 51.940334, 15.514300), \
		(67, 'Starostwo Powiatowe w Bolesławcu', NULL, 51.262319, 15.568434);"

insert_inquiry_sql=" \
	INSERT INTO wnioski_wniosek (id, adresat_id, tytul, opis, wniosek_status, wprowadzenie_data, aktualizacja_data) VALUES \
		(1, 1, 'Nagrody : Urząd Miasta Jelenia Góra', 'Sprawa w toku, wezwaliśmy do wydania decyzji o odmowie udostępnienia informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(2, 2, 'Nagrody : Urząd Miasta Legnica', 'Sprawa w toku, częściowe udostępnienie informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(3, 3, 'Nagrody : Urząd Miejski Wrocławia', 'Sprawa w toku, urząd uznał, że wnioskowaliśmy o informację przetworzoną', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(4, 4, 'Nagrody : Urząd Miejski w Wałbrzychu', 'Sprawa w toku, częściowe udostępnienie informacji - tylko co do tych pracowników samorządowych, którzy są obowiązani do składania oświadczeń majątkowych', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(5, 5, 'Nagrody : Urząd Miasta Bydgoszczy', 'Sprawa w toku, częściowe udostępnienie informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(6, 6, 'Nagrody : Urząd Miejski w Grudziądzu', 'Sprawa  w toku, wydano decyzję o  odmowie udostępnienia informacji publicznej. SKO ją uchyliło, sprawa trafiła do ponownego rozpoznania', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(7, 7, 'Nagrody : Urząd Miasta Torunia', 'Sprawa w toku, brak odpowiedzi na wniosek o udostępnienie informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(8, 8, 'Nagrody : Urząd Miasta Włocławek', 'Sprawa w toku, częściowe udostępnienie informacji - podano ogólne uzasadnienie przyznania nagród co do wszystkich pracowników', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(9, 9, 'Nagrody : Urząd Miasta Biała Podlaska', 'Sprawa w toku, częściowe udostępnienie informacji - co do części pracowników podano konkretne informacje, co do pozostałych - tylko ogólne informacje', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(10, 10, 'Nagrody : Urząd Miasta Chełm', 'Sprawa w toku, częściowe udostępnienie informacji - co do części udostęniono, nie udostępniono informacji co do osób niepełniących funkcje publiczne', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(11, 11, 'Nagrody : Urząd Miasta Lublin', 'Sprawa w toku, częściowo udostępniono w BIP!, co do żądania udostępnienia informacji o pracownikach samorządowych niepełniących funkcji publicznych - wezwano do przeslania podpisanego wniosku', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(12, 12, 'Nagrody : Urząd Miasta Zamość', 'Sprawa zakończona pozytywnie, udostępniono informacje o nagrodzonych (choć uzasadinenie przyznania nagród jest ogólne)', 'CLOSED-SUCCESSFUL', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(13, 13, 'Nagrody : Urząd Miasta Łodzi', 'Sprawa w toku, przedłużono termin do udostępnienia do 21.04.2016, z uwagi na brak odpowiedzi skierowaliśmy skargę na bezczynność', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(14, 14, 'Nagrody : Urząd Miasta Piotrkowa Trybunalskiego', 'Sprawa w toku,nie udostępniono informacji z uwagi na ochronę danych osobowych. Skierowaliśmy skargę na bezczynność', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(15, 15, 'Nagrody : Urząd Miasta Skierniewice', 'Sprawa w toku. Udostępniono częśćiowo informacje o osobach pełniących funkcje publiczne (choć bez szczegółowych uzasadnień). Urząd uznał, że informacje o nagrodach dla osób niepełniących funkcji publicznych to nie jest informacja publiczna', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(16, 16, 'Nagrody : Urząd Miasta Krakowa', 'Sprawa w toku, częściowe udostępnienie informacji, co do częsci - uznanie, że przedmiotem wniosku jest informacja przetworzona - złożyliśmy odwolanie od decyzji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(17, 17, 'Nagrody : Urząd Miasta Nowego Sącza', '', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(18, 18, 'Nagrody : Urząd Miasta Tarnowa', 'Informacja częściowa, udostępniono listę nagrodzonych, ale brak informacji o uzasadnieniu otrzymania nagrody', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(19, 19, 'Nagrody : Urząd Miasta Ostrołęki', '???', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(20, 20, 'Nagrody : Urząd Miasta Płocka', 'Sprawa w toku, częściowe udostępniowe informacji, co do pozostałej części - decyzja o odmowie udostępnienia (o osobach niepełniących funkcji publ).', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(21, 21, 'Nagrody : Urząd Miejski w Radomiu', 'Sprawa w toku, złożono skargę na bezczynność', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(22, 22, 'Nagrody : Urząd Miasta Siedlce', 'Sprawa w toku, informacja wymijająca - zamiast konkretnych informacji, przesłano dane ogólne', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(23, 23, 'Nagrody : Urząd Miasta Stołecznego Warszawy', 'Sprawa zakończona pozytywnie - brak przyznanych nagród na podstawie art.36 ust. 6 ustawy o pracownikach samorządowych', 'CLOSED-SUCCESSFUL', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(24, 24, 'Nagrody : Urząd Miasta Opola', 'Sprawa w toku, częściowe udostępnienie informacji - co do tych, którzy pełnią funkcje publiczne (ale brak uzasadnienia), odmówiono udostępnienia informacji o pracownikach niepełniących funkcji publ. ', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(25, 25, 'Nagrody : Urząd Miasta Krosna', 'Sprawa w toku, częściowo udostępniono informacje o tych, którzy pełnią funkcje publiczne i tych, którzy ich nie pełnią, ale wyrazili zgodę na ujawnienie informacji. Wydano decyzję o odmowie, od której złożyliśmy odwołanie.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(26, 26, 'Nagrody : Urząd Miejski w Przemyślu', '', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(27, 27, 'Nagrody : Urząd Miasta Rzeszowa', 'Sprawa w toku, częściowe udostępnienie informacji (choć ogólne uzasadnienie przyznania nagród), częściowo odmowa udostępnienia informacji publicznej (co do pracowników samorządowych niepełniących funkcji publicznych) - złożyliśmy odwołanie.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(28, 28, 'Nagrody : Urząd Miasta Tarnobrzega', 'Sprawa w toku, częciowe udostępnienie informacji, odmowa udostępnienia informacji co do osób, niepełniących funckje publiczne - złożyliśmy odwołane, SKO podtrzymało, wysłaliśy skargę do sądu. Urząd nie posiada informacji o uzasadnieniach przyznaniach nagród.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(29, 29, 'Nagrody : Urząd Miejski w Białymstoku', '??? Sprawa w toku,  odpowiedź wymijająca, przekazano tylko ogólne dane. Skarga na bezczynność.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(30, 30, 'Nagrody : Urząd Miejski w Łomży', 'Informacja częściowa, udostępniono co do części informacje o nagrodzonych i kwotach (ale nie o uzasadnieniach), w pozostałym zakresie udzielono informacji wymijającej - przekazano ogólne dane o przyznanych nagrodach.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(31, 31, 'Nagrody : Urząd Miejski w Suwałkach', 'Sprawa w toku - urząd uznał, że \"dane dotyczące imion i nazwisk oraz wynagrodzenia wszystkich pracowników\" nie mogą być udostępnione, gdyż nie są to informacje publiczne ', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(32, 32, 'Nagrody : Urząd Miejski w Gdańsku', '???', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(33, 33, 'Nagrody : Urząd Miasta Gdyni', 'Sprawa w toku, urząd uznał, że stowarzyszenie nie ma prawa do informacji publicznej. Złożyliśmy: 1) skargę na bezczynność, 2) zawiadomienie o możliwości popełnienia przestępstwa', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(34, 34, 'Nagrody : Urząd Miejski w Słupsku', 'Sprawa w toku, brak odpowiedzi na wniosek o udostępnienie informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(35, 35, 'Nagrody : Urząd Miasta Sopotu', 'Sprawa w toku, udzielono odpowiedzi wymajającej, gdyż przekazano ogólne dane, a ponadto uznano, że stowarzyszenie nie ma prawa do informacji. Złożyliśmy 1) skargę na bezczynność i 2) zawiadomienie o możliwości popełnienia przestępstwa', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(36, 36, 'Nagrody : Urząd Miejski w Bielsku-Białej', 'Sprawa w toku, udostęniono informacji częściowej, co do pozostałych pracowników. Złożyliśmy skargę na bezczynność w związku z brakiem wydania decyzji odmownej.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(37, 37, 'Nagrody : Urząd Miejski w Bytomiu', 'Sprawa w toku, urząd uznał, że przedmiotem wniosku \"wynagrodzenia pracowników nie są informacja publiczną\". Złożyliśmy skargę na bezczynność', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(38, 38, 'Nagrody : Urząd Miasta Chorzów', 'Sprawa w toku, brak odpowiedzi na wniosek o udostępnienie informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(39, 39, 'Nagrody : Urząd Miasta Częstochowy', 'Sprawa zakończona pozytywnie - przekazano informajcę, że żaden pracownik samorządowy nie otrzymał we wskazanym okresie nagród', 'CLOSED-SUCCESSFUL', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(40, 40, 'Nagrody : Urząd Miejski w Dąbrowie Górniczej', 'Sprawa w toku, odmówiono udostępnienia informacji publicznej, złożyliśmy odwołanie od decyzji odmownej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(41, 41, 'Nagrody : Urząd Miasta Jastrzębie-Zdrój', 'Sprawa w toku, urząd uznał, że wnosiliśmy o udostępnienie informajci przetworzonej i że nie zrealizowaliśmy przesłanki szczególnej istotności dla interesu publicznego. Złożyliśmy odwołanie od decyzji.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(42, 42, 'Nagrody : Urząd Miejski w Jaworznie', 'Sprawa w toku, częściowe udostępnienie informacji, częsciowo odmowa - co do tych pracowników samorządowych, którzy nie posiadają upoważnienia do wydania decyzji administracyjnych', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(43, 43, 'Nagrody : Urząd Miasta Mysłowice', 'Sprawa w toku, urząd uznał, że wnioskowaliśmy o informację przetworzoną. Złożyliśmy odwołanie od decyzji.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(44, 44, 'Nagrody : Urząd Miasta Piekary Śląskie', 'Sprawa zakończona pozytywnie, przeslano listę nagrodzonych pracowników samorządowych wraz z kworami i uzasadnieniem przyznania nagród.', 'CLOSED-SUCCESSFUL', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(45, 45, 'Nagrody : Urząd Miasta Ruda Śląska', 'Sprawa w toku, informacja wymiająca - udzielono listę nagrodzonych pracowników samorządowych, osobno wykaz kwot nagród (ale nie w odniesieniu do konkretnych pracowników). Co do uzasadnień przyznania nagród wskazano ogólnie, że \"Za zaangażowanie w wypełnianiu obowiązków służbowych, przejawianie inicjatywy w pracy i podnoszenie jej wydajności).\"', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(46, 46, 'Nagrody : Urząd Miasta Rybnika', 'Sprawa w toku, urząd uznał, że przedmiotem wniosku było udostępnienie informacji przetworzonej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(47, 47, 'Nagrody : Urząd Miejski w Sosnowcu', 'Sprawa w roku, częsciowo udostępniono informacje publiczną, częściowo odmówiono jej udostępnienia.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(48, 48, 'Nagrody : Urząd Miejski w Świętochłowicach', 'Sprawa w toku, urząd uznał, że wniosek dotyczy informacji przetworzonej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(49, 49, 'Nagrody : Urząd Miasta Tychy', 'Sprawa w toku', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(50, 50, 'Nagrody : Urząd Miejski w Zabrzu', '', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(51, 51, 'Nagrody : Urząd Miasta Żory', 'Sprawa w toku, odmówiono udostępnienia informacji publicznej, złożyliśmy skargę do sądu', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(52, 52, 'Nagrody : Urząd Miejski w Gliwicach', 'Sprawa w toku, częściowe udostępnienie informacji - tylko wobec tych pracowników, którzy pełnią funkcje publiczne, w odniesieniu do pozostałych podano tylko listę nagrodzonych', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(53, 53, 'Nagrody : Urząd Miasta Katowice', 'Sprawa w toku, brak odpowiedzi na wniosek o udostępnienie informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(54, 54, 'Nagrody : Urząd Miasta Siemianowice Śląskie', 'Sprawa w toku, częsciowo udostępniono informację, częściowo odmówiono jej udostępnienia - w tym zakresie złożyliśmy odwołanie od decyzji odmownej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(55, 55, 'Nagrody : Urząd Miasta Kielce', 'Sprawa w toku, częściowo udostępniono informacje dot. pracowników samorządowych pełniących funkcje publiczne, co do pozostałych - udzielono tylko ogólnych informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(56, 56, 'Nagrody : Urząd Miejski w Elblągu', 'Sprawa w toku, w częśći udostępniono informacje, odmówiono udostępnienia informacji dot. pracowników samorządowych niepełniących funkcji publicznych - złożyliśmy odwołanie od decyzji odm9ownej.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(57, 57, 'Nagrody : Urząd Miasta Olsztyna', 'Sprawa w roku, częściowo udostępniono informacje (o tych, którzy pełnią funkcje publiczne), w pozostałym zakresie udzielono tylko ogólnych informacji.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(58, 58, 'Nagrody : Urząd Miejski w Koszalinie', 'Sprawa w toku, w części udostępniono informacje o urzędnikach pełniących funkcje publiczne ,co do pozostałych urzędników - odmówiono udzielenia informacji. Złożyliśmy odwołanie od decyzji odmownej.', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(59, 59, 'Nagrody : Urząd Miasta Szczecin', 'Sprawa w toku, urząd uznał, że przedmiotem wniosku było udostępnienie informacji przetworzonej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(60, 60, 'Nagrody : Urząd Miasta Świnoujście', 'Sprawa w toku, w części udostępniono informacje o pracownikach samorządowych pełniących funkcje publiczne, w pozostałym zakresie udzielono tylko ogólnych informacji', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(61, 61, 'Nagrody : Urząd Miejski w Kaliszu', 'Sprawa w toku, podano tylko ogólne informacje o nagrodach', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(62, 62, 'Nagrody : Urząd Miejski w Koninie', 'Sprawa w toku, w części dot. pracowników pełniących funkcje publiczne udostępniono informacje, w odniesieniu do pozostałych pracowników - odmówiono udostępnienia informacji. Złożyliśmy odwołanie od decyzji odmownej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(63, 63, 'Nagrody : Urząd Miasta Leszna', 'Sprawa w toku, częściowo udostępniono informacje dot. pracowników samorządowych pełniących funkcje publiczne, w pozostałym zakresie wydano decyzję o odmowie. Złożyliśmy od niej odwołanie, SKO przekazało sprawę do ponownego rozpatrzenia', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(64, 64, 'Nagrody : Urząd Miasta Poznania', 'Sprawa w toku, częściowo udostępniono informacje - o nagrodach dla pracowników samorządowych pełniących funkcje publiczne, w pozostałym zakresie uznano, że żądanie nie dotyczy informacji publicznej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(65, 65, 'Nagrody : Urząd Miasta Gorzowa Wielkopolskiego', 'Sprawa w toku, udostępniono konkretne informacje o 4 z 51 pracowników samorządowych, w pozostałym zakresie wydano decyzję administracyjną o odmowie udostępnienia informacji, od ktorej zlożyliśmy odwołanie do SKO..', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(66, 66, 'Nagrody : Urząd Miasta Zielona Góra', 'Sprawa w toku, udzielono wymijającej, ogólnej odpowiedzi i wskazano, że \"przepisy Konstytucji i inne uregulowania prawne zawarte, np. w ustawie o dostępie do informacji publicznej nie przewidują ujawniania tak szczegółowo \"', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'), \
		(67, 67, 'Nagrody : Starostwo Powiatowe w Bolesławcu', 'Sprawa w toku, starostwo uznało, że przedmiotem wniosku było udostępnienie informajci przetworzonej', 'OPEN', '2016-06-06 23:15:14', '2016-06-06 23:15:17'); "
	
# CREATE DATABASE nagrodowy CHARACTER SET utf8;

exec_sql $insert_cities_sql
exec_sql $insert_recieviers_sql
exec_sql $insert_inquiry_sql

# CREATE USER 'nagrodowy'@'localhost' IDENTIFIED BY 'testtest';GRANT USAGE ON *.* TO 'nagrodowy'@'localhost' IDENTIFIED BY 'testtest' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;CREATE DATABASE IF NOT EXISTS nagrodowy CHARACTER SET utf8;GRANT ALL PRIVILEGES ON nagrodowy.* TO 'nagrodowy'@'localhost';
