# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=128, unique=True, verbose_name=b'Adresat')),
                ('szerokosc_geo', models.FloatField(blank=True, null=True, verbose_name=b'Szeroko\xc5\x9b\xc4\x87 geograficzna')),
                ('dlugosc_geo', models.FloatField(blank=True, null=True, verbose_name=b'D\xc5\x82ugo\xc5\x9b\xc4\x87 geograficzna')),
            ],
            options={
                'verbose_name_plural': 'Adresaci',
            },
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64, verbose_name=b'Miasto')),
                ('szerokosc_geo', models.FloatField(blank=True, null=True, verbose_name=b'Szeroko\xc5\x9b\xc4\x87 geograficzna')),
                ('dlugosc_geo', models.FloatField(blank=True, null=True, verbose_name=b'D\xc5\x82ugo\xc5\x9b\xc4\x87 geograficzna')),
            ],
            options={
                'verbose_name_plural': 'Miasta',
            },
        ),
        migrations.CreateModel(
            name='Wniosek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True)),
                ('wniosek_status', models.CharField(choices=[(b'IN-PROGRESS', b'W toku'), (b'IN-PROGRESS-PARTIALLY-FAILED', b'W toku - opinia cz\xc4\x99\xc5\x9bciowo negatywna'), (b'IN-PROGRESS-PARTIALLY-SUCCESSFUL', b'W toku - opinia cz\xc4\x99\xc5\x9bciowo pozytywna'), (b'CLOSED-SUCCESSFUL', b'Zako\xc5\x84czone pomy\xc5\x9blnie'), (b'CLOSED-MOSTLY-SUCCESSFUL', b'Zako\xc5\x84czone g\xc5\x82\xc3\xb3wnie pomy\xc5\x9blnie'), (b'CLOSED-FAILED', b'Zako\xc5\x84czone negatywnie'), (b'CLOSED-MOSTLY-FAILED', b'Zako\xc5\x84czone g\xc5\x82\xc3\xb3wnie negatywnie')], default=b'IN-PROGRESS', max_length=64)),
                ('wprowadzenie_data', models.DateTimeField(default=datetime.datetime(2016, 6, 29, 1, 8, 49, 435033), verbose_name=b'Data wprowadzenia')),
                ('aktualizacja_data', models.DateTimeField(blank=True, null=True, verbose_name=b'Data ostatniej aktualizacji')),
                ('adresat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Adresat')),
            ],
            options={
                'verbose_name_plural': 'Wnioski',
            },
        ),
        migrations.CreateModel(
            name='WniosekHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdarzenie', models.TextField(blank=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Data zdarzenia')),
                ('wniosek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Wniosek')),
            ],
        ),
        migrations.CreateModel(
            name='WniosekZalacznik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(blank=True, max_length=256)),
                ('plik', models.FileField(upload_to=b'.')),
                ('wniosek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Wniosek')),
            ],
            options={
                'verbose_name_plural': 'Za\u0142\u0105czniki do wniosk\xf3w',
            },
        ),
        migrations.AddField(
            model_name='adresat',
            name='miasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wnioski.Miasto'),
        ),
    ]
