# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:42
from __future__ import unicode_literals
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', "initial.json", app_label='wnioski')


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
